workspace = { members = [ "libs/genetic-algorithm","libs/neural-network", "libs/simulation-wasm"] }
[package]
name = "GeneticAlgorithm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
